# Generated by Django 5.0.4 on 2024-04-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_first_name_drivers_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
