# Generated by Django 5.0.4 on 2024-04-25 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_cars_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrigadeNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='brigade',
            name='number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.brigadenumber'),
        ),
    ]
